# Generated by Django 6.1.1 on 2026-09-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("organization", models.CharField(max_length=150)),
                ("designation", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=30)),
                ("country", models.CharField(default="Nepal", max_length=100)),
                ("sector", models.CharField(max_length=100)),
                ("delegate_type", models.CharField(max_length=100)),
                ("interests", models.JSONField(blank=True, default=list)),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
