# Generated by Django 6.1.1 on 2026-09-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="registration",
            name="country",
            field=models.CharField(
                choices=[
                    ("Nepal", "Nepal"),
                    ("United Kingdom", "United Kingdom"),
                    ("Other", "Other"),
                ],
                default="Nepal",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="delegate_type",
            field=models.CharField(
                choices=[
                    ("Government", "Government"),
                    ("Business", "Business"),
                    ("Investor", "Investor"),
                    ("Academic", "Academic"),
                    ("Development Partner", "Development Partner"),
                    ("Technology / Startup", "Technology / Startup"),
                    ("Media", "Media"),
                    ("Other", "Other"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="sector",
            field=models.CharField(
                choices=[
                    ("Government", "Government"),
                    ("Business", "Business"),
                    ("Investment", "Investment"),
                    ("Education & research", "Education & research"),
                    ("Development", "Development"),
                    ("Technology & startup", "Technology & startup"),
                    ("Media", "Media"),
                    ("Other", "Other"),
                ],
                max_length=100,
            ),
        ),
    ]
