# Generated by Django 6.1.1 on 2026-09-17 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_contact_alter_registration_country_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Contact enquiry",
                "verbose_name_plural": "Contact enquiries",
            },
        ),
        migrations.AlterModelOptions(
            name="registration",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Registration",
                "verbose_name_plural": "Registrations",
            },
        ),
        migrations.AlterField(
            model_name="registration",
            name="phone",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number.",
                        regex="^[+0-9()\\s-]{7,}$",
                    )
                ],
            ),
        ),
    ]
